// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBApFny0NHgW6cYWKjhTSU2F5AufGkAKYk',
    appId: '1:269100512848:web:1d71c0bd0d43767ddc8355',
    messagingSenderId: '269100512848',
    projectId: 'voiceup-24bce',
    authDomain: 'voiceup-24bce.firebaseapp.com',
    storageBucket: 'voiceup-24bce.firebasestorage.app',
    measurementId: 'G-FPMWTT7QTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZl3cfsJIlcg1ElVMVSj9IEj1fgtU-kYc',
    appId: '1:269100512848:android:6944ba17db7e6198dc8355',
    messagingSenderId: '269100512848',
    projectId: 'voiceup-24bce',
    storageBucket: 'voiceup-24bce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDxf93CBZ9qTybhMY0Z8LWosA_4oquQc',
    appId: '1:269100512848:ios:2ec7105a001d1bf0dc8355',
    messagingSenderId: '269100512848',
    projectId: 'voiceup-24bce',
    storageBucket: 'voiceup-24bce.firebasestorage.app',
    iosBundleId: 'com.example.voiceup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDxf93CBZ9qTybhMY0Z8LWosA_4oquQc',
    appId: '1:269100512848:ios:2ec7105a001d1bf0dc8355',
    messagingSenderId: '269100512848',
    projectId: 'voiceup-24bce',
    storageBucket: 'voiceup-24bce.firebasestorage.app',
    iosBundleId: 'com.example.voiceup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBApFny0NHgW6cYWKjhTSU2F5AufGkAKYk',
    appId: '1:269100512848:web:02bbafe14a900394dc8355',
    messagingSenderId: '269100512848',
    projectId: 'voiceup-24bce',
    authDomain: 'voiceup-24bce.firebaseapp.com',
    storageBucket: 'voiceup-24bce.firebasestorage.app',
    measurementId: 'G-1NZCD6RBBM',
  );
}
